config/routes.rb
Rails.application.routes.draw do

  resources :posts

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :posts
	validates :name, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end
	
	def show
		@post = Post.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Portfolio Cośtam</h1>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Lista postów</h1>

<ul>
	<% @posts.each do |post| %>
		<li><%= link_to post.title, post_path(post) %></li>
	<% end %>
</ul>

app/views/posts/show.html.erb
<%= link_to "All posts", posts_path %>
<%= @post.title %>